CREATE DATABASE "DATABASE_NAME_XXX"
    WITH 
    OWNER = postgres
    ENCODING = 'UTF8'
    LC_COLLATE = 'COLLATION_NAME_XXX'
    LC_CTYPE = 'COLLATION_NAME_XXX'
    TABLESPACE = pg_default
    CONNECTION LIMIT = -1;
ALTER ROLE postgres IN DATABASE "DATABASE_NAME_XXX"
    SET application_name TO DEFAULT;
GRANT TEMPORARY, CONNECT ON DATABASE "DATABASE_NAME_XXX TO PUBLIC;
GRANT ALL ON DATABASE "DATABASE_NAME_XXX" TO postgres;