// Help_ids.inc
//
// Context ids. This uses help file Developer5.chm.
//
// This is a sample version. YOU must supply
// the ID values

//  Generic Context Ids
//
Define SQLConnectionsProgram for 0
#REPLACE KeysHelpId              0
#REPLACE FileHelpId              0

// It is expected that file-names ids will be the same as their
// filenumber.


//  View and selection-list specific context ids
//
//..........add view, object, selection-list ids here....